

puts ""
@a = gets.chomp.upcase.chars.reject{|w| w == " "}.join.to_sym
def acroyn

dataacroyn = {:DNA => "Deoxynucleic Acid", :RNA => "Ribonucleic Acid", :IS => "Insertion Sequence"}
dataacroyn[@a]
end

puts acroyn
#Linkage
require_relative 'Linkage/crossover'

#Cells and Chromosomes
require_relative 'Cells and Chromosomes/cells'
require_relative 'Cells and Chromosomes/centroindex'
require_relative 'Cells and Chromosomes/MeioChromoDis'
require_relative 'Cells and Chromosomes/pqarm'

#MENDELIAN GENETICS
require_relative 'Mendelian Genetics/dihybrid'
require_relative 'Mendelian Genetics/Genopercent'
require_relative 'Mendelian Genetics/Genoratio'
require_relative 'Mendelian Genetics/indeassort'
require_relative 'Mendelian Genetics/monohybrid'
require_relative 'Mendelian Genetics/posgenotypes'
require_relative 'Mendelian Genetics/segrega'
require_relative 'Mendelian Genetics/selfcross'
require_relative 'Mendelian Genetics/Testcross'
require_relative 'Mendelian Genetics/trihybrid'
#SEX DETERMINATION
require_relative 'Sex Determination/barrbody'
require_relative 'Sex Determination/dsex'
#MENDELIAN EXTENSION
require_relative 'Mendelian Extension/bloodg'
require_relative 'Mendelian Extension/gametophytic'
require_relative 'Mendelian Extension/incompletedominance'
require_relative 'Mendelian Extension/MultiAlleleCombination'
require_relative 'Mendelian Extension/MultipleAlleleP'
require_relative 'Mendelian Extension/nallele'
require_relative 'Mendelian Extension/pieotropy'
require_relative 'Mendelian Extension/sexinflutraits'
require_relative 'Mendelian Extension/Sporophytic'

#Chromoosme Variation
require_relative 'Chromosome Variation/mprefixploid/mdecaploid'
require_relative 'Chromosome Variation/mprefixploid/mdiploid'
require_relative 'Chromosome Variation/mprefixploid/mheptaploid'
require_relative 'Chromosome Variation/mprefixploid/mhexaploid'
require_relative 'Chromosome Variation/mprefixploid/mnonaploid'
require_relative 'Chromosome Variation/mprefixploid/moctaploid'
require_relative 'Chromosome Variation/mprefixploid/mpentaploid'
require_relative 'Chromosome Variation/mprefixploid/mtetraploid'
require_relative 'Chromosome Variation/mprefixploid/mtriploid'

require_relative 'Chromosome Variation/prefixmonoploid/decamonoploid'
require_relative 'Chromosome Variation/prefixmonoploid/dimonoploid'
require_relative 'Chromosome Variation/prefixmonoploid/heptamonoploid'
require_relative 'Chromosome Variation/prefixmonoploid/hexamonoploid'
require_relative 'Chromosome Variation/prefixmonoploid/nonamonoploid'
require_relative 'Chromosome Variation/prefixmonoploid/octamonoploid'
require_relative 'Chromosome Variation/prefixmonoploid/pentamonoploid'
require_relative 'Chromosome Variation/prefixmonoploid/tetramonoplioid'
require_relative 'Chromosome Variation/prefixmonoploid/trimonoploid'

require_relative 'Chromosome Variation/Somics/disomic'
require_relative 'Chromosome Variation/Somics/monosomic'
require_relative 'Chromosome Variation/Somics/doubletrisomic'
require_relative 'Chromosome Variation/Somics/nullisomic'
require_relative 'Chromosome Variation/Somics/tetrasomic'
require_relative 'Chromosome Variation/Somics/trisomic'
require_relative 'Chromosome Variation/Somys/doublemonosomy'
require_relative 'Chromosome Variation/Somys/doubletrisomy'
require_relative 'Chromosome Variation/Somys/monosomy'
require_relative 'Chromosome Variation/Somys/nullisomy'
require_relative 'Chromosome Variation/Somys/tetrasomy'
require_relative 'Chromosome Variation/Somys/triplemonosomy'
require_relative 'Chromosome Variation/Somys/trisomy'
require_relative 'Chromosome Variation/chromodupli'
require_relative 'Chromosome Variation/chromoinversion'
require_relative 'Chromosome Variation/colchicine'
require_relative 'Chromosome Variation/Polyseries'
#ViralRNA
require_relative 'Bacteria and Viruses/viralRNA'
                                        # Molecular Genetics
#Chemical Structure of DNA
require_relative 'Chemical Structure of DNA/Adenine'
require_relative 'Chemical Structure of DNA/AssignRYN'
require_relative 'Chemical Structure of DNA/basepair'
require_relative 'Chemical Structure of DNA/char'
require_relative 'Chemical Structure of DNA/chargaff'
require_relative 'Chemical Structure of DNA/complimentarystrand'
require_relative 'Chemical Structure of DNA/Cytosine'
require_relative 'Chemical Structure of DNA/dibond'
require_relative 'Chemical Structure of DNA/dnainum'
require_relative 'Chemical Structure of DNA/Guanine'
require_relative 'Chemical Structure of DNA/Leastbase'
require_relative 'Chemical Structure of DNA/Modebase'
require_relative 'Chemical Structure of DNA/ModeleastNbases'
require_relative 'Chemical Structure of DNA/Nucleopercent'
require_relative 'Chemical Structure of DNA/nucleotides'
require_relative 'Chemical Structure of DNA/numtdna'
require_relative 'Chemical Structure of DNA/phosphate'
require_relative 'Chemical Structure of DNA/purines'
require_relative 'Chemical Structure of DNA/pyrimidine'
require_relative 'Chemical Structure of DNA/strand'
require_relative 'Chemical Structure of DNA/sugarnum'
require_relative 'Chemical Structure of DNA/SumEachBase'
require_relative 'Chemical Structure of DNA/Thymine'
require_relative 'Chemical Structure of DNA/TotalSequence'
require_relative 'Chemical Structure of DNA/tribond'
require_relative 'Chromosome Structure/meltingDNA'
require_relative 'Chromosome Structure/telomere'
require_relative 'Epigenetics/sobisulf'
require_relative 'Genomics/freqd'
require_relative 'Genomics/freqr'
require_relative 'Genomics/pos'
require_relative 'Transcription/conseq'
require_relative 'Transcription/rnadidna'
require_relative 'Transcription/unbaseq'
require_relative 'Transcription/updownstream'
require_relative 'Gene Expression/polyatail'
require_relative 'Gene Expression/Spliceosome'
require_relative 'Molecular Genetics/ATRatio'
require_relative 'Molecular Genetics/BluntEnds'
require_relative 'Molecular Genetics/buildpalindromic'
require_relative 'Molecular Genetics/chopdna'
require_relative 'Molecular Genetics/CohesiveEnds'
require_relative 'Molecular Genetics/defloures'
require_relative 'Molecular Genetics/denature'
require_relative 'Molecular Genetics/EcoRI'
require_relative 'Molecular Genetics/floures'
require_relative 'Molecular Genetics/GCRatio'
require_relative 'Molecular Genetics/gelelectro'
require_relative 'Molecular Genetics/NaOH'
require_relative 'Molecular Genetics/palindromic'
require_relative 'Genetic Code/AminoPercent'
require_relative 'Genetic Code/AromaticAmino'
require_relative 'Genetic Code/ChargeAmino'
require_relative 'Genetic Code/degenerate'
require_relative 'Genetic Code/findcodon'
require_relative 'Genetic Code/firstopcodon'
require_relative 'Genetic Code/NonaromaticAmino'
require_relative 'Genetic Code/NonpolarAmino'
require_relative 'Genetic Code/polaramino'
require_relative 'Genetic Code/porypho'
require_relative 'Genetic Code/SpecialAmino'
require_relative 'Genetic Code/triplecodonum'
require_relative 'RNA Molecule/numtrna'
require_relative 'RNA Molecule/rnacomp'
require_relative 'RNA Molecule/rna-dna'
require_relative 'RNA Molecule/rnainum'
require_relative 'RNA Molecule/uracil'

#Mendelian Genetics
#Generating dihybridcross


